services:
  postgres:
    image: postgres:14.5-bullseye
    container_name: ${DB_CONTAINER}
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - bill_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${PG_CONTAINER}
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:80"


volumes:
  bill_data:
    name: bill_data