services:
  bill-api:
    build: ./bill-api
    image: aarooon16045/bill-api:latest
    ports: 
      - "5005:5040"
    restart: on-failure
    working_dir: /srv/bill-api
    env_file:
      - .env.${ENV}
    networks:
      - database-network

  bill-frontend:
    image: aarooon16045/app-frontend:${TAG:-latest}
    ports:
      - "5004:80"                # matches EXPOSE 5004 and nginx.conf
    env_file:
      - .env.${ENV}


networks:
  database-network:
    external: true